# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby_bosh}
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pradeep Elankumaran"]
  s.date = %q{2011-05-03}
  s.description = %q{An XMPP BOSH session pre-initializer for Ruby web applications}
  s.email = %q{pradeep@intridea.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "TODO"
  ]
  s.files = [
    "LICENSE",
    "README",
    "Rakefile",
    "TODO",
    "VERSION.yml",
    "autotest/discover.rb",
    "lib/ruby_bosh.rb",
    "ruby_bosh.gemspec",
    "spec/ruby_bosh_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/skyfallsin/ruby_bosh}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A BOSH session pre-initializer for Ruby web applications}
  s.test_files = [
    "spec/ruby_bosh_spec.rb",
    "spec/spec_helper.rb"
  ]

  s.add_dependency 'builder'
  s.add_dependency 'rest-client'
  s.add_dependency 'pry'
  s.add_dependency 'nokogiri'
end

